 Q1) Multiples of 3 or 5
 If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3,5,6 and 9. The sum of these multiples is 23
Find the sum of all the multiples of 3 or 5 below 1000.

In [1]:
sum=0
for i in range(1000):
    if i%3==0 or i%5==0:
        sum=sum+i
print("The sum of all the multiples of 3 and 5 below 1000 is:",sum)

The sum of all the multiples of 3 and 5 below 1000 is: 233168

Q2) Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1,2,3,5,8,13,21,34,55,89
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [2]:
L=[]
sum=0
for i in range(1,50):
    L.append(i)
L[0]=1
L[1]=2
List=[]
for i in range(len(L)):
    if i!=0 and i!=1:
        L[i]=L[i-1]+L[i-2]
    if L[i]<4000000:
        if L[i]%2==0:
            List.append(L[i])
print(List)
for i in range(len(List)):
    sum=sum+List[i]
print("The sum is:",sum)

[2, 8, 34, 144, 610, 2584, 10946, 46368, 196418, 832040, 3524578]
The sum is: 4613732

Q6) Sum Square Difference

In [4]:
sum0,sum1=0,0
for i in range(101):
    sum0=sum0+(i**2)
    sum1=(sum1+i)
square=sum1**2
print("sum of the squares of the first hundred natural numbers:",sum0)
print("square of the sum of the first hundred natural numbers is:",square)
print("difference between the sum of the squares of the first one hundred natural numbers and the square of the sum is:",square-sum0)

sum of the squares of the first hundred natural numbers: 338350
square of the sum of the first hundred natural numbers is: 25502500
difference between the sum of the squares of the first one hundred natural numbers and the square of the sum is: 25164150

Q7) 10001st Prime

In [ ]:
L=[]
x=300000
for i in range(2,x):
    for j in range(2,i):
        if i%j==0:
            break
    else:
        L.append(i)
for i in range(30000,300000):
    for j in range(2,i):
        if i%j==0:
            break
    else:
        L.append(i)
print(L[10000])

Q 10) Summation of Primes

In [ ]:
n=2000000
sum=0
for i in range(2,n+1):
    for j in range(2,i):
        if i%j==0:
            break
    else:
        sum=sum+i
print(sum)